function truthy(key: string) {
  const value = process.env[key]?.toLowerCase()
  return value === "true" || value === "1"
}

function number(key: string) {
  const value = process.env[key]
  if (!value) return undefined
  const parsed = Number(value)
  return Number.isInteger(parsed) && parsed > 0 ? parsed : undefined
}

function computeFlags() {
  const OPENCODE_DISABLE_CLAUDE_CODE = truthy("OPENCODE_DISABLE_CLAUDE_CODE")
  const OPENCODE_EXPERIMENTAL = truthy("OPENCODE_EXPERIMENTAL")

  return {
    OPENCODE_AUTO_SHARE: truthy("OPENCODE_AUTO_SHARE"),
    OPENCODE_GIT_BASH_PATH: process.env["OPENCODE_GIT_BASH_PATH"],
    OPENCODE_CONFIG: process.env["OPENCODE_CONFIG"],
    OPENCODE_CONFIG_DIR: process.env["OPENCODE_CONFIG_DIR"],
    OPENCODE_CONFIG_CONTENT: process.env["OPENCODE_CONFIG_CONTENT"],
    OPENCODE_DISABLE_AUTOUPDATE: truthy("OPENCODE_DISABLE_AUTOUPDATE"),
    OPENCODE_DISABLE_PRUNE: truthy("OPENCODE_DISABLE_PRUNE"),
    OPENCODE_DISABLE_TERMINAL_TITLE: truthy("OPENCODE_DISABLE_TERMINAL_TITLE"),
    OPENCODE_PERMISSION: process.env["OPENCODE_PERMISSION"],
    OPENCODE_DISABLE_DEFAULT_PLUGINS: truthy("OPENCODE_DISABLE_DEFAULT_PLUGINS"),
    OPENCODE_DISABLE_LSP_DOWNLOAD: truthy("OPENCODE_DISABLE_LSP_DOWNLOAD"),
    OPENCODE_ENABLE_EXPERIMENTAL_MODELS: truthy("OPENCODE_ENABLE_EXPERIMENTAL_MODELS"),
    OPENCODE_DISABLE_AUTOCOMPACT: truthy("OPENCODE_DISABLE_AUTOCOMPACT"),
    OPENCODE_DISABLE_MODELS_FETCH: truthy("OPENCODE_DISABLE_MODELS_FETCH"),
    OPENCODE_DISABLE_CLAUDE_CODE,
    OPENCODE_DISABLE_CLAUDE_CODE_PROMPT:
      OPENCODE_DISABLE_CLAUDE_CODE || truthy("OPENCODE_DISABLE_CLAUDE_CODE_PROMPT"),
    OPENCODE_DISABLE_CLAUDE_CODE_SKILLS:
      OPENCODE_DISABLE_CLAUDE_CODE || truthy("OPENCODE_DISABLE_CLAUDE_CODE_SKILLS"),
    OPENCODE_FAKE_VCS: process.env["OPENCODE_FAKE_VCS"],
    OPENCODE_CLIENT: process.env["OPENCODE_CLIENT"] ?? "cli",
    AGENT_CORE_SERVER_PASSWORD: process.env["AGENT_CORE_SERVER_PASSWORD"],
    AGENT_CORE_SERVER_USERNAME: process.env["AGENT_CORE_SERVER_USERNAME"],
    OPENCODE_SERVER_PASSWORD: process.env["OPENCODE_SERVER_PASSWORD"],
    OPENCODE_SERVER_USERNAME: process.env["OPENCODE_SERVER_USERNAME"],
    AGENT_CORE_DISABLE_SERVER_AUTH: truthy("AGENT_CORE_DISABLE_SERVER_AUTH"),
    OPENCODE_DISABLE_SERVER_AUTH: truthy("OPENCODE_DISABLE_SERVER_AUTH"),
    AGENT_CORE_ENABLE_SERVER_AUTH: truthy("AGENT_CORE_ENABLE_SERVER_AUTH"),
    OPENCODE_ENABLE_SERVER_AUTH: truthy("OPENCODE_ENABLE_SERVER_AUTH"),

    // Experimental
    OPENCODE_EXPERIMENTAL,
    OPENCODE_EXPERIMENTAL_FILEWATCHER: truthy("OPENCODE_EXPERIMENTAL_FILEWATCHER"),
    OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER: truthy("OPENCODE_EXPERIMENTAL_DISABLE_FILEWATCHER"),
    OPENCODE_EXPERIMENTAL_ICON_DISCOVERY: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_ICON_DISCOVERY"),
    OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT: truthy("OPENCODE_EXPERIMENTAL_DISABLE_COPY_ON_SELECT"),
    OPENCODE_ENABLE_EXA: truthy("OPENCODE_ENABLE_EXA") || OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_EXA"),
    OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH: number("OPENCODE_EXPERIMENTAL_BASH_MAX_OUTPUT_LENGTH"),
    OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS: number("OPENCODE_EXPERIMENTAL_BASH_DEFAULT_TIMEOUT_MS"),
    OPENCODE_EXPERIMENTAL_LLM_STREAM_START_TIMEOUT_MS: number("OPENCODE_EXPERIMENTAL_LLM_STREAM_START_TIMEOUT_MS"),
    OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX: number("OPENCODE_EXPERIMENTAL_OUTPUT_TOKEN_MAX"),
    OPENCODE_EXPERIMENTAL_OXFMT: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_OXFMT"),
    OPENCODE_EXPERIMENTAL_LSP_TY: truthy("OPENCODE_EXPERIMENTAL_LSP_TY"),
    OPENCODE_EXPERIMENTAL_LSP_TOOL: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_LSP_TOOL"),
    OPENCODE_EXPERIMENTAL_PLAN_MODE: OPENCODE_EXPERIMENTAL || truthy("OPENCODE_EXPERIMENTAL_PLAN_MODE"),
  }
}

export const Flag = computeFlags()

export function reloadFlags() {
  Object.assign(Flag, computeFlags())
}

